- hosts: all
  become_user: root
  become_method: sudo
  roles:
    - apt
    - nano
    - bashrc
    - htop
    - icinga2-snapshot
    - icinga2
    - monitoring-plugins
    - icinga2-ido-mysql
    - icingaweb2
